version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: auth-user
      POSTGRES_PASSWORD: auth-pass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  auth-data:
